# Obter a lista de usuários
GET http://localhost:3000/api/usuarios
Content-Type: application/json
###

# Inserir novo usuário
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
"nome": "Jaqson Dalbosco", "email": "jaqson@upf.br",
"celular": "99999-9999", "senha": "123",
"dataHoraCad": "2021-01-25T17:32:25.000Z"
}
###


# Alterar usuário
PUT http://localhost:3000/api/usuarios
Content-Type: application/json

{
"_id": "6127ea2e9ea79b27117eec69",
"nome": "beltrano alterado",
"email": "beltrano@teste.com",
"celular": "54 6543 2423"
}
###
# Excluir um usuário
DELETE http://localhost:3000/api/usuarios/6127ea2e9ea79b27117eec69
Content-Type: application/json
###
# Obter pelo id de usuário
GET http://localhost:3000/api/usuarios/5f6cb80e07cee54810920f5f
Content-Type: application/json
###
# Obter usuários filtrando
GET http://localhost:3000/api/usuarios/filtro/fulano
Content-Type: application/js