@apiUrl = http://localhost:3000/api/projetos

# Obter a lista de usuários
GET http://localhost:3000/api/projetos
Content-Type: application/json
###

# Inserir novo usuário
POST http://localhost:3000/api/projetos
Content-Type: application/json

{
  "titulo": "Projeto teste",
  "descricao": "teste descricao",
  "dataInicio": "02/09/2021",
  "DataTermino": "05/09/2021",
  "nomeDemandante": "Fulano",
  "responsavel" : "612831004576432f4084643f"
} 
###

# Alterar usuário
PUT http://localhost:3000/api/projetos
Content-Type: application/json

{
 "_id": "612830ef4576432f40846439",
 "nome": "beltrano alterado",
 "email": "beltrano@teste.com",
 "celular": "54 6543 2423"
}
###
# Excluir um usuário
DELETE http://localhost:3000/api/projetos/612830ef4576432f40846439
Content-Type: application/json
###
# Obter pelo id de usuário
GET http://localhost:3000/api/projetos/612830ef4576432f40846439
Content-Type: application/json
###
# Obter usuários filtrando
GET http://localhost:3000/api/projetos/filtro/Felipe
Content-Type: application/json
###


