@apiUrl = http://localhost:3000/api

# Autenticação de usuário
POST {{apiUrl}}/login
Content-Type: application/json

{
 "email": "felipe@upf.br",
 "senha": "123"
}
###

# Autenticação de usuário
POST {{apiUrl}}/login
Content-Type: application/json

{
 "email": "166382@upf.br",
 "senha": "123"
}
###